=== Mikhail2k15/bot-framework-schema/caap-message.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Microsoft CaaP (Conversation as a Platform) Message Schema",
    "description": "Message envelope schema for Bot Framework and Skype.",

    "type": "object",
	"required": [ "type", "timestamp", "from", "conversation", "recipient" ],
	"additionalProperties": false,
    "properties": {
		"type": {
			"$ref": "#/definitions/messageType",
			"description": "Defines what kind of message is being sent."
		},
		"id": {
			"type": "string",
			"description": "The unique identifier of a user message the bot message is a reply to (needed in certain scenarios)."
		},
		"timestamp": {
			"type": "string",
			"format": "date-time",
			"description": "Timestamp of the message in ISO8601 format, e.g. '2016-06-15T03:48:50.3817037Z'."
		},
		"serviceUrl": {
			"$ref": "#/definitions/uri",
			"description": "The channel-specific endpoint to which replies to the message should be sent."
		},
		"channelId": {
			"$ref": "#/definitions/channelIds",
			"description": "The unique identifier for the channel from which a message was sent."
		},
		"from": {
			"$ref": "#/definitions/conversationParticipant",
			"description": "The person or bot sending the message."
		},
		"conversation": {
			"$ref": "#/definitions/conversationInfo",
			"description": "Metadata about the conversation the message is a part of."
		},
		"recipient": {
			"$ref": "#/definitions/conversationParticipant",
			"description": "The person or bot receiving the message."
		},
		"text": {
			"type": "string",
			"description": "The text of the message."
		},
		"textFormat": {
			"$ref": "#/definitions/textFormats",
			"description": "Describes the format of the text property (plain, markdown, xml, etc.)."
		},
		"summary": {
			"type": "string",
			"description": "Describes the contents of complex messages."
		},
		"replyToId": {
			"type": "string",
			"description": "The ID of the message this message is in reply to. Optional if the message is not a reply."
		},
		"entities": {
			"type": "array",
			"items": {
				"type": "object"
			},
			"description": "Array of schema.org entities"
		},
		"attachments": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/attachment"
			},
			"description": "Array of attachments to the message."
		},
		"attachmentLayout": {
			"$ref": "#/definitions/attachmentLayouts",
			"description": "Layout hints for attachments (e.g. list, carousel, etc.)"
		},
		"channelData": {
			"type": [ "boolean", "integer", "number", "string", "array", "object", "null" ], 
			"description": "Channel-specific metadata."
		}
    },

    "definitions": {
		"messageType": {
			"enum": [
				"message",
              	"conversationUpdate", 
				"contactUpdate",
				"typing"
			],
			"description": "The set of valid types for a message."
		},
		"channelIds": {
			"enum": [
				"emulator", 
				"email",
				"facebookMessenger", 
				"groupMe",
				"kik",
				"skype", 
				"skypeTeams", 
				"slack",
				"telegram",
				"text/sms",
				"web"
			],
			"description": "The set of valid channel identifiers."
		},
		"conversationParticipant": {
			"type": "object",
			"properties": {
				"id": {
					"type": "string",
					"description": "Unique identifier of the person or bot sending or receiving the message."
				},
				"name": {
					"type": "string",
					"description": "User-visible name for the person or bot sending or receiving the message."
				}
			},
			"required": [ "id", "name" ]
		},
		"conversationInfo": {
			"type": "object",
			"properties": {
				"id": {
					"type": "string",
					"description": "Unique identifier for the conversation."
				},
				"isGroup": {
					"type": "boolean",
					"description": "Indicates whether the conversation is 1:1 or 1:M."
				}
			},
			"required": [ "id" ]
		},		
		"textFormats": {
			"enum": [
				"plain",
              	"markdown", 
				"xml"
			],
			"description": "The set of types for the text property of the message."
		},
		"attachmentLayouts": {
			"enum": [
				"list",
              	"carousel"
			],
			"description": "The set of layout hints for cards in the attachment collection."
		},
		"attachment": {
			"type": "object",
			"properties": {
				"contentType": {
					"type": "string",
					"description": "MIME type of the attachment."
				},
				"content": {
					"type": "object",
					"description": "Object schema of contentType."
				},
				"contentUrl": {
					"$ref": "#/definitions/uri",
					"description": "Reference to location of attachment content."
				}
			},
			"required": [ "contentType" ]
		},
		"uri": {
			"type": "string",
			"format": "uri"
		}
    }
}

=== Mikhail2k15/bot-framework-schema/channeldata-message.json
{
  "type": "message",
  "timestamp": "2016-06-20T19:15:40.6819535Z",
  "from": {
    "id": "42166681",
    "name": "TestBot"
  },
  "conversation": {
    "id": "8a684db5",
    "name": "Conv2"
  },
  "recipient": {
    "id": "2c1c7fa3",
    "name": "User1"
  },
  "text": "Address:11 Conversation:11 UserInConversation:11 channeldata",
  "channelData": {
    "prop": "property value"
  },
  "replyToId": "440d27d561e143cc809732832883b952"
}

=== Mikhail2k15/bot-framework-schema/thumbnail-message.json
{
  "type": "message",
  "timestamp": "2016-06-20T19:13:57.1091478Z",
  "from": {
    "id": "42166681",
    "name": "TestBot"
  },
  "conversation": {
    "id": "8a684db5",
    "name": "Conv2"
  },
  "recipient": {
    "id": "2c1c7fa3",
    "name": "User1"
  },
  "textFormat": "markdown",
  "text": "",
  "summary": "Thumbnail Card about bender",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.thumbnail",
      "content": {
        "title": "Bender",
        "subtitle": "tale of a robot who dared to love",
        "text": "Bender Bending Rodr√≠guez is a main character in the animated television series Futurama. He was created by series creators Matt Groening and David X. Cohen, and is voiced by John DiMaggio",
        "images": [
          {
            "url": "https://upload.wikimedia.org/wikipedia/en/a/a6/Bender_Rodriguez.png",
            "alt": "Bender_Rodriguez"
          }
        ],
        "buttons": [
          {
            "type": "imBack",
            "title": "Thumbs Up",
            "image": "http://moopz.com/assets_c/2012/06/emoji-thumbs-up-150-thumb-autox125-140616.jpg",
            "value": "I like it"
          },
          {
            "type": "imBack",
            "title": "Thumbs Down",
            "image": "http://yourfaceisstupid.com/wp-content/uploads/2014/08/thumbs-down.png",
            "value": "I don't like it"
          },
          {
            "type": "openUrl",
            "title": "I feel lucky",
            "image": "http://thumb9.shutterstock.com/photos/thumb_large/683806/148441982.jpg",
            "value": "https://www.bing.com/images/search?q=bender&qpvt=bender&qpvt=bender&qpvt=bender&FORM=IGRE"
          }
        ],
        "tap": {
          "type": "imBack",
          "value": "Tapped it!"
        }
      }
    }
  ],
  "replyToId": "d45734ee41664c6d8993436175e23337"
}

=== Mikhail2k15/bot-framework-schema/signin-message.json
{
  "type": "message",
  "timestamp": "2016-06-15T06:14:38.9741981Z",
  "from": {
    "id": "42166681",
    "name": "TestBot"
  },
  "conversation": {
    "id": "8a684db5",
	"name": "Conv2"
  },
  "recipient": {
    "id": "2c1c7fa3",
    "name": "User1"
  },
  "text": "",
  "summary": "Request to sign in",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.signin",
      "content": {
        "title": "I need your credentials to steal all of your money",
        "button": {
          "type": "signin",
          "title": "Signin",
          "value": "https://login.live.com/login.srf?wa=wsignin1.0&ct=1464753247&rver=6.6.6556.0&wp=MBI_SSL&wreply=https:%2F%2Foutlook.live.com%2Fowa%2F&id=292841&CBCXT=out"
        }
      }
    }
  ],
  "replyToId": "5b43c64c5dd84b39a3fe1f65358276fc"
}

=== Mikhail2k15/bot-framework-schema/directmessage-message.json
{
  "type": "message",
  "id": "a2ca94d96f184e72921506d97b25f079",
  "timestamp": "2016-06-20T19:16:35.5112008Z",
  "serviceUrl": "https://12ee5529.ngrok.io",
  "channelId": "emulator",
  "from": {
    "id": "2c1c7fa3",
    "name": "User1"
  },
  "conversation": {
    "isGroup": false,
    "id": "8a684db5",
    "name": "Conv2"
  },
  "recipient": {
    "id": "42166681",
    "name": "TestBot"
  },
  "text": "dm",
  "attachments": [],
  "entities": []
}

=== Mikhail2k15/bot-framework-schema/help-message.json
{
  "type": "message",
  "timestamp": "2016-06-20T19:14:35.8804117Z",
  "from": {
    "id": "42166681",
    "name": "TestBot"
  },
  "conversation": {
    "id": "8a684db5",
    "name": "Conv2"
  },
  "recipient": {
    "id": "2c1c7fa3",
    "name": "User1"
  },
  "text": "",
  "summary": "list of commands as buttons",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "Commands",
        "buttons": [
          {
            "type": "imBack",
            "title": "carousel",
            "value": "carousel"
          },
          {
            "type": "imBack",
            "title": "channeldata",
            "value": "channeldata"
          },
          {
            "type": "imBack",
            "title": "codeSample",
            "value": "codeSample"
          },
          {
            "type": "imBack",
            "title": "dm",
            "value": "dm"
          },
          {
            "type": "imBack",
            "title": "document",
            "value": "document"
          },
          {
            "type": "imBack",
            "title": "emojii",
            "value": "emojii"
          },
          {
            "type": "imBack",
            "title": "help",
            "value": "help"
          },
          {
            "type": "imBack",
            "title": "hero",
            "value": "hero"
          },
          {
            "type": "imBack",
            "title": "images",
            "value": "images"
          },
          {
            "type": "imBack",
            "title": "list",
            "value": "list"
          },
          {
            "type": "imBack",
            "title": "markdown",
            "value": "markdown"
          },
          {
            "type": "imBack",
            "title": "members",
            "value": "members"
          },
          {
            "type": "imBack",
            "title": "paragraph",
            "value": "paragraph"
          },
          {
            "type": "imBack",
            "title": "receipt",
            "value": "receipt"
          },
          {
            "type": "imBack",
            "title": "runall",
            "value": "runall"
          },
          {
            "type": "imBack",
            "title": "signin",
            "value": "signin"
          },
          {
            "type": "imBack",
            "title": "thumbnail",
            "value": "thumbnail"
          },
          {
            "type": "imBack",
            "title": "typing",
            "value": "typing"
          },
          {
            "type": "imBack",
            "title": "upload",
            "value": "upload"
          },
          {
            "type": "imBack",
            "title": "video",
            "value": "video"
          }
        ]
      }
    }
  ],
  "replyToId": "c0c5851f011844a3a963097c9cb07985"
}

=== Mikhail2k15/bot-framework-schema/carousel-message.json
{
  "type": "message",
  "timestamp": "2016-06-20T18:35:36.5360234Z",
  "from": {
    "id": "42166681",
    "name": "TestBot"
  },
  "conversation": {
    "id": "8a684db5",
    "name": "Conv2"
  },
  "recipient": {
    "id": "2c1c7fa3",
    "name": "User1"
  },
  "textFormat": "plain",
  "attachmentLayout": "carousel",
  "text": "test carousel",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "Details about Alfani Voyage Synthetic Wedge Sandal",
        "text": "Price: $17.99 USD",
        "images": [
          {
            "url": "https://tse2.mm.bing.net/th?id=OIP.M7c063034a5e451261019b98f0f9c991co0&pid=Api"
          }
        ],
        "buttons": [
          {
            "type": "imBack",
            "title": "Places to buy",
            "value": "Places To Buy"
          },
          {
            "type": "imBack",
            "title": "Related Products",
            "value": "Related Products"
          }
        ]
      }
    },
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "Bandolino Gurrey Womens Size 9.5 Pink Wedge Sandals Shoes",
        "text": "Price: $17.99 USD",
        "images": [
          {
            "url": "https://tse2.mm.bing.net/th?id=OIP.M1977ca518c034a35854840ce535eed5ao0&pid=Api"
          }
        ],
        "buttons": [
          {
            "type": "imBack",
            "title": "Places to buy",
            "value": "Places To Buy"
          },
          {
            "type": "imBack",
            "title": "Related Products",
            "value": "Related Products"
          }
        ]
      }
    },
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "Sonoran Flat Sandals Womens Shoes - b.o.c. B?rn Concept ...",
        "text": "Price: $85 USD",
        "images": [
          {
            "url": "https://tse4.mm.bing.net/th?id=OIP.M0a6173fef7e25f6deab58116ccd981b0o0&pid=Api"
          }
        ],
        "buttons": [
          {
            "type": "imBack",
            "title": "Places to buy",
            "value": "Places To Buy"
          },
          {
            "type": "imBack",
            "title": "Related Products",
            "value": "Related Products"
          }
        ]
      }
    },
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "Style & Co. Jodii Platform Wedge Thong Sandals Womens Shoes",
        "text": "Price: $14.57 USD",
        "images": [
          {
            "url": "https://tse2.mm.bing.net/th?id=OIP.M17a60132d0ed2ee6127a269d71c39c49o0&pid=Api"
          }
        ],
        "buttons": [
          {
            "type": "imBack",
            "title": "Places to buy",
            "value": "Places To Buy"
          },
          {
            "type": "imBack",
            "title": "Related Products",
            "value": "Related Products"
          }
        ]
      }
    }
  ],
  "replyToId": "072aff016be14565b5bba17eb27f4bcd"
}
